FROM ubuntu:xenial
# TODO LABEL maintainer="Name <email-address>"

# generally useful packages
RUN apt-get update && apt-get install -y --no-install-recommends \
        ca-certificates \
        apt-transport-https \
        curl \
        wget \
        vim \
        git \
        procps \
        autoconf \
        automake \
        g++ \
        gcc \
        make \
        pkg-config \
        zip \
        unzip \
    && rm -rf /var/lib/apt/lists/*


# install fpm
ENV FPM_VERSION=1.9.3
RUN apt-get update && apt-get install -y --no-install-recommends \
        ruby \
        ruby-dev \
        rubygems \
    && gem install --no-ri --no-rdoc fpm -v $FPM_VERSION \
    && rm -rf /var/lib/apt/lists/*


# install gosu to simplify stepping down from root
# https://github.com/tianon/gosu/blob/master/INSTALL.md#from-debian
ENV GOSU_VERSION 1.10
RUN set -x \
	&& wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
	&& wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" \
	&& export GNUPGHOME="$(mktemp -d)" \
	&& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
	&& gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
	&& rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc \
	&& chmod +x /usr/local/bin/gosu \
	&& gosu nobody true


# TODO CMD ENTRYPOINT ...

ENV BASE_ENV_VERSION=0.3.0
