version: "3.4"

services:

  base:
    build:
      context: ./base/$OSNAME
      network: ${DOCKER_BUILD_NETWORK:-bridge}
      args:
          - INDY_SDK_VERSION
          - u_id=${DOCKER_UID}
    image: ${LSTBASE_DOCKER_NAME}:${LSTBASE_DOCKER_TAG}

  ci:
    build:
      context: ./ci/$OSNAME
      network: ${DOCKER_BUILD_NETWORK:-bridge}
    image: ${CI_DOCKER_NAME}:${CI_DOCKER_TAG}
