version: 0.2

# TODO
#   - is it ok that artifacts phase is executed even if the BUILD phase fails
#       https://docs.aws.amazon.com/codebuild/latest/userguide/view-build-details.html#view-build-details-phases
#   - publish to crates.io

env:
  variables:
    # expected
    OSNAME: ""
    MAKE_GOALS: ""
    CARGO_TARGET_DIR: "target"
    # optional
    ARTIFACTS: ""
    INDY_POOL_LOG_LEVEL: ""
    INDY_POOL_DIRS: "/tmp /var/lib/indy/sandbox /var/log/indy/sandbox"

phases:

  pre_build:
    commands:
      - echo Pre-Build started on `date`
      # create soft link dockerfile like 'start_pool'
      - libsovtoken-ci-entrypoint.sh
      - mkdir -p /tmp/artifacts/logs/pool
  build:
    commands:
      - echo Build started on `date`
      - printenv
      - export PROJECT_DIR="$PWD"
      - |
        set -ex
        for goal in $MAKE_GOALS; do
            echo "Making '$goal'"
            /bin/bash -c "set -o pipefail; make -C devops $goal 2>&1 | tee /tmp/artifacts/logs/${OSNAME}.${goal}.log"
        done
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing artifacts
      - |
        set -ex
        # nodes' logs and validators info for failed builds
        if [ "$CODEBUILD_BUILD_SUCCEEDING" != "1" -a -n "$INDY_POOL_DIRS" ]; then
            find $INDY_POOL_DIRS -maxdepth 1 -type f \
                \( -iname \node*.log -o -iname \node*.json \) \
                -exec zip -j '{}'.zip '{}' \; \
                -exec mv '{}'.zip /tmp/artifacts/logs/pool \; \
            || true
        fi
        # additional artifacts
        for art in $ARTIFACTS; do
            cp -vR -t /tmp/artifacts $art || true
        done
      - find /tmp/artifacts

artifacts:
  # (for now CodeBuild doesn't allow to use env variables in artifacts phase)
  # https://forums.aws.amazon.com/thread.jspa?threadID=250742
  base-directory: /tmp/artifacts
  files:
      - '**/*'
