name: Libsovtoken - PR Workflow
on:
  pull_request:
    paths:
      - '**'
      - '!libsovtoken/Cargo.toml'
     
jobs:
  workflow-setup:
    name: Initialize Workflow
    runs-on: ubuntu-latest
    outputs:
      CACHE_KEY_BUILD: ${{ steps.setup.outputs.CACHE_KEY_BUILD }}
      CACHE_KEY_POOL: ${{ steps.pool_setup.outputs.CACHE_KEY_POOL }}
      UBUNTU_VERSION: ${{ steps.setup.outputs.UBUNTU_VERSION }}
      # Expose the lowercase version of the GitHub repository name
      # to all subsequent jobs that reference image repositories
      # as the push and pull operations require the URL of the repository
      # to be in lowercase.
      GITHUB_REPOSITORY_NAME: ${{ steps.setup.outputs.GITHUB_REPOSITORY_NAME }}
      distribution: ${{ steps.setup.outputs.distribution }}
      publish: ${{ steps.setup.outputs.publish }}
      testsNeeded: ${{ steps.testsNeeded.outputs.testsNeeded }}
      newVersion : ${{ steps.version.outputs.newVersion }}
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
      - name: setup
        id: setup
        uses: hyperledger/indy-shared-gha/.github/actions/workflow-setup@v1
        with:
          ownerRepo: "sovrin-foundation"
      - name: setup pool data
        id: pool_setup
        run: |
          echo "CACHE_KEY_POOL=${{ hashFiles('devops/indy-pool/Dockerfile') }}" >> $GITHUB_OUTPUT
          echo "::group::DEBUG"
          echo "CACHE_KEY-POOL is set to ${{ hashFiles('devops/indy-pool/Dockerfile') }}"
          echo "::endgroup::"
      - name: testsNeeded
        id: testsNeeded
        uses: dorny/paths-filter@v2
        with:
          filters: |
            testsNeeded:
              - '**.rs'
              - '.github/**'
              - '**.toml'
      - id: version
        uses: ./.github/actions/reuseable_bumpVersion

  build-image:  
    name: Create DIND Image
    needs: [workflow-setup]
    if: ${{ needs.workflow-setup.outputs.testsNeeded == 'true' }}
    uses: hyperledger/indy-shared-gha/.github/workflows/buildimage.yaml@v1
    with:
      CACHE_KEY_BUILD: ${{ needs.workflow-setup.outputs.CACHE_KEY_BUILD }}
      DOCKER_IMAGE: ghcr.io/${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}/libsovtoken-dind
      UBUNTU_VERSION: ${{ needs.workflow-setup.outputs.UBUNTU_VERSION }}
  
  build-pool-image:
    name: Create Pool Image
    needs: [workflow-setup]
    uses: ./.github/workflows/reuseable_build_pool.yaml
    with:
      CACHE_KEY_POOL: ${{ needs.workflow-setup.outputs.CACHE_KEY_POOL }}
      DOCKER_IMAGE: ghcr.io/${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}/libsovtoken-pool

  build-and-test:
    name: Build and build-and-test
    needs: [workflow-setup,build-image, build-pool-image]
    uses: ./.github/workflows/reuseable_buildAndTest.yaml
    with:
      GITHUB_REPOSITORY_NAME: ${{ needs.workflow-setup.outputs.GITHUB_REPOSITORY_NAME }}
      newVersion: ${{ needs.workflow-setup.outputs.newVersion }}

  statusCheck:
    name: statusCheck
    runs-on: ubuntu-latest
    needs: [workflow-setup, build-and-test]
    if: ${{ needs.workflow-setup.outputs.testsNeeded == 'false' || success() }}
    steps:
      - run: 'echo "Just a status Check (Always true, when executed) for branch protection rules(blocks merging while test are running and if tests fail)." '