name: "Build Indy Pool"

on:
  workflow_call:
    inputs:
      DOCKER_IMAGE:
          required: true
          type: string
      CACHE_KEY_POOL:
        required: true
        type: string
jobs:
  build-pool-image:
    runs-on: ubuntu-latest
    env:
      CACHE_KEY_POOL: ${{ inputs.CACHE_KEY_POOL }}
      DOCKER_IMAGE: ${{ inputs.DOCKER_IMAGE }}    
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Try load from cache
        id: cache-image
        uses: actions/cache@v3
        with:
          path: ${GITHUB_WORKSPACE}/cache
          key: ${{ env.CACHE_KEY_POOL }}

      - name: Prepare image labels and tags
        if: steps.cache-image.outputs.cache-hit != 'true'
        id: prep
        shell: bash
        run: |
          TAGS="${DOCKER_IMAGE}:latest"
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

          echo "::group::DEBUG"
          echo "tags=${TAGS}" 
          echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          echo "::endgroup::"

      - name: Log into the GitHub Container Registry
        if: steps.cache-image.outputs.cache-hit != 'true'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: steps.cache-image.outputs.cache-hit != 'true'
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        if: steps.cache-image.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v3
        with:
          context: devops/indy-pool/
          file: devops/indy-pool/Dockerfile
          no-cache: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          build-args: pool_ip=192.168.0.2
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Touch Cache
        if: steps.cache-image.outputs.cache-hit != 'true'
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/cache
          touch ${GITHUB_WORKSPACE}/cache/${{ env.CACHE_KEY_BUILD }}