name: "Build and Test"

on:
  workflow_call:
    inputs:
      GITHUB_REPOSITORY_NAME:
          required: true
          type: string
      newVersion:
        required: false
        default: "noBump"
        type: string
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/${{ inputs.GITHUB_REPOSITORY_NAME }}/libsovtoken-dind:latest
      options: --privileged
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Log into the GitHub Container Registry
        if: steps.cache-image.outputs.cache-hit != 'true'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with: 
          components: clippy
      
      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-bump cargo-deb
        run: cargo install cargo-bump cargo-deb

      - name: Cargo Bump version
        if: ${{ inputs.newVersion }} != "noBump"
        run: cargo bump ${{ inputs.newVersion }} --manifest-path libsovtoken/Cargo.toml

      - name: Lint with clippy
        continue-on-error: true
        run: cargo clippy --manifest-path libsovtoken/Cargo.toml

      - name: Set up Indy Pool and Docker network
        run: |
          docker network create poolnet --subnet 192.168.0.0/16
          docker run -itd -p 9701-9708:9701-9708 --network poolnet --ip 192.168.0.2 ghcr.io/${{ inputs.GITHUB_REPOSITORY_NAME }}/libsovtoken-pool:latest
          docker network connect poolnet $(cat /etc/hostname)
          
      - name: Test libsovtoken
        env:
          TEST_POOL_IP: 192.168.0.2
        run: cargo test --manifest-path libsovtoken/Cargo.toml -- --test-threads=1

      - name: Build 
        run: cargo build --release --manifest-path libsovtoken/Cargo.toml

      - name: Build deb package
        run: cargo deb --manifest-path libsovtoken/Cargo.toml

      - name: Upload deb
        uses: actions/upload-artifact@v3
        with:
          name: libsovtoken-deb
          path: libsovtoken/target/debian/*.deb
          retention-days: 5
          
      - uses: actions/upload-artifact@v3
        with:
          name: libsovtoken-build
          path: libsovtoken/target/release
          retention-days: 5