name: Triggered by set Tag

on:
  push:
    tags:
      - setRelease-v**

jobs:
  taginfos:
    name: get Tag infos
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-release-info.outputs.version }}
      versionTag: ${{ steps.get-release-info.outputs.versionTag }}
      prBranch: ${{ steps.get-release-info.outputs.prBranch }}
      BASE: ${{ steps.get-branch.outputs.branch }}
    steps:
      - name: checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: extract branch 
        id: get-branch
        uses: hyperledger/indy-shared-gha/.github/actions/branch-from-tag@v1
        with:
          tag: ${{ github.ref }}
      - name: get-release-info
        id: get-release-info
        uses: hyperledger/indy-shared-gha/.github/actions/get-release-info@v1
        with:
          versionString: "${{ github.ref }}"


  bump_version:
    name: Bump Version Number
    needs: taginfos
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with: 
          components: clippy
      
      - name: Cache cargo resources
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-bump
        run: cargo install cargo-bump

      - name: Cargo Bump version
        run: cargo bump ${{ needs.taginfos.outputs.version }} --manifest-path libsovtoken/Cargo.toml
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          author: ${{ github.actor }} <${{ github.event.pusher.email }}>
          committer: ${{ github.actor }} <${{ github.event.pusher.email }}>
          signoff: true
          commit-message: Update Version number for v${{ needs.taginfos.outputs.version }}
          base: ${{ needs.taginfos.outputs.BASE }}
          branch: ${{ needs.taginfos.outputs.prBranch }}
          title: "[${{ needs.taginfos.outputs.versionTag }}] - Update Version Number for Release"
          body: "[${{ needs.taginfos.outputs.versionTag }}] - Update Version number for Release"
          delete-branch: true
          token: ${{ secrets.BOT_PR_PAT }}
